name: Sample Workflow
on: 
  push:
    branches: [ main ]
env:
  audience: EY
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello script
        run: echo "hello"
      - name: check the node-version
        run: |
          node -v
          npm -v
      - name: Say hello
        run: echo "Hello $audience"
        
  github-actions-variables:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job is triggered by ${{ github.event_name }}"
        
